---
openapi: 3.0.0
info:
  title: Dredd Testing Demo
  description: Laravel Dredd Testing Documentation
  version: v2
servers:
  - url: test.dev
    description: test Server

paths:
  "/api/posts":
    $ref: "./paths/posts.yml"
  "/api/posts/{post_id}":
    $ref: "./paths/posts-post-id.yml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
  requestBodies:
  responses:
